package cn.ticket.entity;


public class Admins {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_admin.wxs_id
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private Integer Id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_admin.wxs_account
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_admin.wxs_password
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_admin.wxs_email
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_admin.wxs_address
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String address;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_admin.wxs_id
	 * @return  the value of table_wxs_admin.wxs_id
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public Integer getId() {
		return Id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_admin.wxs_id
	 * @param Id  the value for table_wxs_admin.wxs_id
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setId(Integer Id) {
		this.Id = Id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_admin.wxs_account
	 * @return  the value of table_wxs_admin.wxs_account
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_admin.wxs_account
	 * @param account  the value for table_wxs_admin.wxs_account
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_admin.wxs_password
	 * @return  the value of table_wxs_admin.wxs_password
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_admin.wxs_password
	 * @param password  the value for table_wxs_admin.wxs_password
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_admin.wxs_email
	 * @return  the value of table_wxs_admin.wxs_email
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_admin.wxs_email
	 * @param email  the value for table_wxs_admin.wxs_email
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_admin.wxs_address
	 * @return  the value of table_wxs_admin.wxs_address
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_admin.wxs_address
	 * @param address  the value for table_wxs_admin.wxs_address
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	public Admins() {
		super();
	}

	public Admins(String account, String password) {
		super();
		this.account = account;
		this.password = password;
	}
	

	public Admins(Integer id, String account, String password) {
		super();
		Id = id;
		this.account = account;
		this.password = password;
	}
	

	public Admins(Integer id, String account, String password, String email,
			String address) {
		super();
		Id = id;
		this.account = account;
		this.password = password;
		this.email = email;
		this.address = address;
	}
	

	public Admins(String account, String password, String email, String address) {
		super();
		this.account = account;
		this.password = password;
		this.email = email;
		this.address = address;
	}

	@Override
	public String toString() {
		return "Admins [account=" + account + ", password=" + password + "]";
	}

}