package cn.ticket.entity;

public class Back {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_back.wxs_id
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_back.wxs_name
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_back.wxs_email
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_back.wxs_content
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_back.wxs_date
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_back.wxs_status
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private Integer status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_back.wxs_id
	 * @return  the value of table_wxs_back.wxs_id
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_back.wxs_id
	 * @param id  the value for table_wxs_back.wxs_id
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_back.wxs_name
	 * @return  the value of table_wxs_back.wxs_name
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_back.wxs_name
	 * @param name  the value for table_wxs_back.wxs_name
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_back.wxs_email
	 * @return  the value of table_wxs_back.wxs_email
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_back.wxs_email
	 * @param email  the value for table_wxs_back.wxs_email
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_back.wxs_content
	 * @return  the value of table_wxs_back.wxs_content
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_back.wxs_content
	 * @param content  the value for table_wxs_back.wxs_content
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_back.wxs_date
	 * @return  the value of table_wxs_back.wxs_date
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_back.wxs_date
	 * @param date  the value for table_wxs_back.wxs_date
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setDate(String date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_back.wxs_status
	 * @return  the value of table_wxs_back.wxs_status
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_back.wxs_status
	 * @param status  the value for table_wxs_back.wxs_status
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	public Back() {
		super();
	}

	public Back(Integer id, String name, String email, String content,
			String date, Integer status) {
		super();
		this.id = id;
		this.name = name;
		this.email = email;
		this.content = content;
		this.date = date;
		this.status = status;
	}

	public Back(String name, String email, String content, String date) {
		super();
		this.name = name;
		this.email = email;
		this.content = content;
		this.date = date;
		this.status = 0;
	}

	@Override
	public String toString() {
		return "Back [id=" + id + ", name=" + name + ", email=" + email
				+ ", content=" + content + ", date=" + date + ", status="
				+ status + "]";
	}

}