package cn.ticket.entity;

public class Notice {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_notice.wxs_id
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_notice.wxs_content
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_notice.wxs_id
	 * @return  the value of table_wxs_notice.wxs_id
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_notice.wxs_id
	 * @param id  the value for table_wxs_notice.wxs_id
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_notice.wxs_content
	 * @return  the value of table_wxs_notice.wxs_content
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_notice.wxs_content
	 * @param content  the value for table_wxs_notice.wxs_content
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}

	public Notice(Integer id, String content) {
		super();
		this.id = id;
		this.content = content;
	}

	public Notice(String content) {
		super();
		this.content = content;
	}

	public Notice() {
		super();
	}

	@Override
	public String toString() {
		return "Notice [id=" + id + ", content=" + content + "]";
	}
	

}