package cn.ticket.entity;

public class Orders {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_orders.wxs_order_num
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private Long orderNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_orders.wxs_trains_num
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String trainsNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_orders.wxs_seat_num
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private Integer seatNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_orders.wxs_total_price
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private Float totalPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_orders.wxs_custom_id
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String customId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_orders.wxs_account
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_orders.wxs_custom_name
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String customName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_orders.wxs_date
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_orders.wxs_ticket_status
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private Integer ticketStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_orders.wxs_departure_place
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String departPlace;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_orders.wxs_destination
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String destination;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_orders.wxs_departure_time
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String departTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_orders.wxs_ticket_barrier
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private Integer ticketBarrier;




	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_orders.wxs_order_num
	 * @return  the value of table_wxs_orders.wxs_order_num
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public Long getOrderNum() {
		return orderNum;
	}




	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_orders.wxs_order_num
	 * @param orderNum  the value for table_wxs_orders.wxs_order_num
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setOrderNum(Long orderNum) {
		this.orderNum = orderNum;
	}




	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_orders.wxs_trains_num
	 * @return  the value of table_wxs_orders.wxs_trains_num
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getTrainsNum() {
		return trainsNum;
	}




	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_orders.wxs_trains_num
	 * @param trainsNum  the value for table_wxs_orders.wxs_trains_num
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setTrainsNum(String trainsNum) {
		this.trainsNum = trainsNum;
	}




	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_orders.wxs_seat_num
	 * @return  the value of table_wxs_orders.wxs_seat_num
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public Integer getSeatNum() {
		return seatNum;
	}




	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_orders.wxs_seat_num
	 * @param seatNum  the value for table_wxs_orders.wxs_seat_num
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setSeatNum(Integer seatNum) {
		this.seatNum = seatNum;
	}




	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_orders.wxs_total_price
	 * @return  the value of table_wxs_orders.wxs_total_price
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public Float getTotalPrice() {
		return totalPrice;
	}




	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_orders.wxs_total_price
	 * @param totalPrice  the value for table_wxs_orders.wxs_total_price
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setTotalPrice(Float totalPrice) {
		this.totalPrice = totalPrice;
	}




	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_orders.wxs_custom_id
	 * @return  the value of table_wxs_orders.wxs_custom_id
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getCustomId() {
		return customId;
	}




	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_orders.wxs_custom_id
	 * @param customId  the value for table_wxs_orders.wxs_custom_id
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setCustomId(String customId) {
		this.customId = customId;
	}




	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_orders.wxs_account
	 * @return  the value of table_wxs_orders.wxs_account
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getAccount() {
		return account;
	}




	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_orders.wxs_account
	 * @param account  the value for table_wxs_orders.wxs_account
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setAccount(String account) {
		this.account = account;
	}




	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_orders.wxs_custom_name
	 * @return  the value of table_wxs_orders.wxs_custom_name
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getCustomName() {
		return customName;
	}




	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_orders.wxs_custom_name
	 * @param customName  the value for table_wxs_orders.wxs_custom_name
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setCustomName(String customName) {
		this.customName = customName;
	}




	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_orders.wxs_date
	 * @return  the value of table_wxs_orders.wxs_date
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getDate() {
		return date;
	}




	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_orders.wxs_date
	 * @param date  the value for table_wxs_orders.wxs_date
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setDate(String date) {
		this.date = date;
	}




	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_orders.wxs_ticket_status
	 * @return  the value of table_wxs_orders.wxs_ticket_status
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public Integer getTicketStatus() {
		return ticketStatus;
	}




	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_orders.wxs_ticket_status
	 * @param ticketStatus  the value for table_wxs_orders.wxs_ticket_status
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setTicketStatus(Integer ticketStatus) {
		this.ticketStatus = ticketStatus;
	}




	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_orders.wxs_departure_place
	 * @return  the value of table_wxs_orders.wxs_departure_place
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getDepartPlace() {
		return departPlace;
	}




	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_orders.wxs_departure_place
	 * @param departPlace  the value for table_wxs_orders.wxs_departure_place
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setDepartPlace(String departPlace) {
		this.departPlace = departPlace;
	}




	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_orders.wxs_destination
	 * @return  the value of table_wxs_orders.wxs_destination
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getDestination() {
		return destination;
	}




	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_orders.wxs_destination
	 * @param destination  the value for table_wxs_orders.wxs_destination
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setDestination(String destination) {
		this.destination = destination;
	}




	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_orders.wxs_departure_time
	 * @return  the value of table_wxs_orders.wxs_departure_time
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getDepartTime() {
		return departTime;
	}




	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_orders.wxs_departure_time
	 * @param departTime  the value for table_wxs_orders.wxs_departure_time
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setDepartTime(String departTime) {
		this.departTime = departTime;
	}




	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_orders.wxs_ticket_barrier
	 * @return  the value of table_wxs_orders.wxs_ticket_barrier
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public Integer getTicketBarrier() {
		return ticketBarrier;
	}




	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_orders.wxs_ticket_barrier
	 * @param ticketBarrier  the value for table_wxs_orders.wxs_ticket_barrier
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setTicketBarrier(Integer ticketBarrier) {
		this.ticketBarrier = ticketBarrier;
	}




	public Orders() {
		super();
	}




	public Orders(Long orderNum, String trainsNum, Integer seatNum,
			Float totalPrice, String customId, String account,
			String customName, String date, Integer ticketStatus,
			String departPlace, String destination, String departTime,
			Integer ticketBarrier) {
		super();
		this.orderNum = orderNum;
		this.trainsNum = trainsNum;
		this.seatNum = seatNum;
		this.totalPrice = totalPrice;
		this.customId = customId;
		this.account = account;
		this.customName = customName;
		this.date = date;
		this.ticketStatus = ticketStatus;
		this.departPlace = departPlace;
		this.destination = destination;
		this.departTime = departTime;
		this.ticketBarrier = ticketBarrier;
	}




	public Orders(String trainsNum, Integer seatNum, Float totalPrice,
			String customId, String account, String customName, String date,
			Integer ticketStatus, String departPlace, String destination,
			String departTime, Integer ticketBarrier) {
		super();
		this.trainsNum = trainsNum;
		this.seatNum = seatNum;
		this.totalPrice = totalPrice;
		this.customId = customId;
		this.account = account;
		this.customName = customName;
		this.date = date;
		this.ticketStatus = ticketStatus;
		this.departPlace = departPlace;
		this.destination = destination;
		this.departTime = departTime;
		this.ticketBarrier = ticketBarrier;
	}




	@Override
	public String toString() {
		return "Orders [orderNum=" + orderNum + ", trainsNum=" + trainsNum
				+ ", seatNum=" + seatNum + ", totalPrice=" + totalPrice
				+ ", customId=" + customId + ", account=" + account
				+ ", customName=" + customName + ", date=" + date
				+ ", ticketStatus=" + ticketStatus + ", departPlace="
				+ departPlace + ", destination=" + destination
				+ ", departTime=" + departTime + ", ticketBarrier="
				+ ticketBarrier + "]";
	}




}