package cn.ticket.entity;

public class PassagerInfo {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_passager_info.wxs_id
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_passager_info.wxs_name
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_passager_info.wxs_id
	 * @return  the value of table_wxs_passager_info.wxs_id
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_passager_info.wxs_id
	 * @param id  the value for table_wxs_passager_info.wxs_id
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_passager_info.wxs_name
	 * @return  the value of table_wxs_passager_info.wxs_name
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_passager_info.wxs_name
	 * @param name  the value for table_wxs_passager_info.wxs_name
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	public PassagerInfo() {
		super();
	}

	public PassagerInfo(String id, String name) {
		super();
		this.id = id;
		this.name = name;
	}

	@Override
	public String toString() {
		return "PassagerInfo [id=" + id + ", name=" + name + "]";
	}
 
}