package cn.ticket.entity;

public class Tickets {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_ticket.wxs_ticket_id
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private Long Id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_ticket.wxs_trains_num
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String trainsNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_ticket.wxs_bus_type
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private Integer busType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_ticket.wxs_departure_place
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String departPlace;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_ticket.wxs_destination
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String destination;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_ticket.wxs_departure_time
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String departureTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_ticket.wxs_ticket_price
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private Float ticketPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_ticket.wxs_count
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private Integer count;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_ticket.wxs_ticket_barrier
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private Integer ticketBarrier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_ticket.wxs_seat_residual
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String seatResidual;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_ticket.wxs_date
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String date;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_ticket.wxs_ticket_id
	 * @return  the value of table_wxs_ticket.wxs_ticket_id
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public Long getId() {
		return Id;
	}



	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_ticket.wxs_ticket_id
	 * @param Id  the value for table_wxs_ticket.wxs_ticket_id
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setId(Long Id) {
		this.Id = Id;
	}



	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_ticket.wxs_trains_num
	 * @return  the value of table_wxs_ticket.wxs_trains_num
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getTrainsNum() {
		return trainsNum;
	}



	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_ticket.wxs_trains_num
	 * @param trainsNum  the value for table_wxs_ticket.wxs_trains_num
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setTrainsNum(String trainsNum) {
		this.trainsNum = trainsNum;
	}



	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_ticket.wxs_bus_type
	 * @return  the value of table_wxs_ticket.wxs_bus_type
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public Integer getBusType() {
		return busType;
	}



	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_ticket.wxs_bus_type
	 * @param busType  the value for table_wxs_ticket.wxs_bus_type
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setBusType(Integer busType) {
		this.busType = busType;
	}



	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_ticket.wxs_departure_place
	 * @return  the value of table_wxs_ticket.wxs_departure_place
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getDepartPlace() {
		return departPlace;
	}



	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_ticket.wxs_departure_place
	 * @param departPlace  the value for table_wxs_ticket.wxs_departure_place
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setDepartPlace(String departPlace) {
		this.departPlace = departPlace;
	}



	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_ticket.wxs_destination
	 * @return  the value of table_wxs_ticket.wxs_destination
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getDestination() {
		return destination;
	}



	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_ticket.wxs_destination
	 * @param destination  the value for table_wxs_ticket.wxs_destination
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setDestination(String destination) {
		this.destination = destination;
	}



	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_ticket.wxs_departure_time
	 * @return  the value of table_wxs_ticket.wxs_departure_time
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getDepartureTime() {
		return departureTime;
	}



	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_ticket.wxs_departure_time
	 * @param departureTime  the value for table_wxs_ticket.wxs_departure_time
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setDepartureTime(String departureTime) {
		this.departureTime = departureTime;
	}



	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_ticket.wxs_ticket_price
	 * @return  the value of table_wxs_ticket.wxs_ticket_price
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public Float getTicketPrice() {
		return ticketPrice;
	}



	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_ticket.wxs_ticket_price
	 * @param ticketPrice  the value for table_wxs_ticket.wxs_ticket_price
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setTicketPrice(Float ticketPrice) {
		this.ticketPrice = ticketPrice;
	}



	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_ticket.wxs_count
	 * @return  the value of table_wxs_ticket.wxs_count
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public Integer getCount() {
		return count;
	}



	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_ticket.wxs_count
	 * @param count  the value for table_wxs_ticket.wxs_count
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setCount(Integer count) {
		this.count = count;
	}



	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_ticket.wxs_ticket_barrier
	 * @return  the value of table_wxs_ticket.wxs_ticket_barrier
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public Integer getTicketBarrier() {
		return ticketBarrier;
	}



	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_ticket.wxs_ticket_barrier
	 * @param ticketBarrier  the value for table_wxs_ticket.wxs_ticket_barrier
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setTicketBarrier(Integer ticketBarrier) {
		this.ticketBarrier = ticketBarrier;
	}



	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_ticket.wxs_seat_residual
	 * @return  the value of table_wxs_ticket.wxs_seat_residual
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getSeatResidual() {
		return seatResidual;
	}



	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_ticket.wxs_seat_residual
	 * @param seatResidual  the value for table_wxs_ticket.wxs_seat_residual
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setSeatResidual(String seatResidual) {
		this.seatResidual = seatResidual;
	}



	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_ticket.wxs_date
	 * @return  the value of table_wxs_ticket.wxs_date
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getDate() {
		return date;
	}



	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_ticket.wxs_date
	 * @param date  the value for table_wxs_ticket.wxs_date
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setDate(String date) {
		this.date = date;
	}



	public Tickets() {
		super();
	}



	public Tickets(Long id, String trainsNum, Integer busType,
			String departPlace, String destination, String departureTime,
			Float ticketPrice, Integer count, Integer ticketBarrier,
			String seatResidual, String date) {
		super();
		Id = id;
		this.trainsNum = trainsNum;
		this.busType = busType;
		this.departPlace = departPlace;
		this.destination = destination;
		this.departureTime = departureTime;
		this.ticketPrice = ticketPrice;
		this.count = count;
		this.ticketBarrier = ticketBarrier;
		this.seatResidual = seatResidual;
		this.date = date;
	}

	
	public Tickets(String trainsNum, Integer busType, String departPlace,
			String destination, String departureTime, Float ticketPrice,
			Integer count, Integer ticketBarrier, String seatResidual,
			String date) {
		super();
		this.trainsNum = trainsNum;
		this.busType = busType;
		this.departPlace = departPlace;
		this.destination = destination;
		this.departureTime = departureTime;
		this.ticketPrice = ticketPrice;
		this.count = count;
		this.ticketBarrier = ticketBarrier;
		this.seatResidual = seatResidual;
		this.date = date;
	}

	@Override
	public String toString() {
		return "Tickets [Id=" + Id + ", trainsNum=" + trainsNum + ", busType="
				+ busType + ", departPlace=" + departPlace + ", destination="
				+ destination + ", departureTime=" + departureTime
				+ ", ticketPrice=" + ticketPrice + ", count=" + count
				+ ", ticketBarrier=" + ticketBarrier + ", seatResidual="
				+ seatResidual + ", date=" + date + "]";
	}


}