package cn.ticket.entity;

public class Users {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_users.wxs_account
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_users.wxs_password
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_users.wxs_balance
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private Float balance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_users.wxs_email
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_users.wxs_card_id
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String cardId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column table_wxs_users.wxs_name
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_users.wxs_account
	 * @return  the value of table_wxs_users.wxs_account
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_users.wxs_account
	 * @param account  the value for table_wxs_users.wxs_account
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_users.wxs_password
	 * @return  the value of table_wxs_users.wxs_password
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_users.wxs_password
	 * @param password  the value for table_wxs_users.wxs_password
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_users.wxs_balance
	 * @return  the value of table_wxs_users.wxs_balance
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public Float getBalance() {
		return balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_users.wxs_balance
	 * @param balance  the value for table_wxs_users.wxs_balance
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setBalance(Float balance) {
		this.balance = balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_users.wxs_email
	 * @return  the value of table_wxs_users.wxs_email
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_users.wxs_email
	 * @param email  the value for table_wxs_users.wxs_email
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_users.wxs_card_id
	 * @return  the value of table_wxs_users.wxs_card_id
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getCardId() {
		return cardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_users.wxs_card_id
	 * @param cardId  the value for table_wxs_users.wxs_card_id
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setCardId(String cardId) {
		this.cardId = cardId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column table_wxs_users.wxs_name
	 * @return  the value of table_wxs_users.wxs_name
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column table_wxs_users.wxs_name
	 * @param name  the value for table_wxs_users.wxs_name
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	public Users(String account, String password, Float balance, String email,
			String cardId, String name) {
		super();
		this.account = account;
		this.password = password;
		this.balance = balance;
		this.email = email;
		this.cardId = cardId;
		this.name = name;
	}

	public Users() {
		super();
	}

	@Override
	public String toString() {
		return "Users [account=" + account + ", passwored=" + password
				+ ", balance=" + balance + ", email=" + email + ", cardId="
				+ cardId + "]";
	}

}