package cn.ticket.dao;

import org.springframework.stereotype.Repository;

import cn.ticket.entity.Admins;

@Repository
public interface AdminsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_admin
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int deleteByPrimaryKey(Integer Id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_admin
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int insert(Admins record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_admin
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int insertSelective(Admins record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_admin
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	Admins selectByPrimaryKey(Integer Id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_admin
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int updateByPrimaryKeySelective(Admins record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_admin
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int updateByPrimaryKey(Admins record);

	//	查询帐户
	Admins selectByAccount(String account);
}