package cn.ticket.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import cn.ticket.entity.Back;

@Repository
public interface BackMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_back
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_back
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int insert(Back record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_back
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int insertSelective(Back record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_back
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	Back selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_back
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int updateByPrimaryKeySelective(Back record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_back
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int updateByPrimaryKey(Back record);

	//	通过指定初始记录的索引�?获取列表
	List<Back> getBackListByDate(Long start);
	
//	获取相关列表总数
	Long getNum();
}