package cn.ticket.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import cn.ticket.entity.Notice;

@Repository
public interface NoticeMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_notice
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_notice
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int insert(Notice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_notice
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int insertSelective(Notice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_notice
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	Notice selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_notice
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int updateByPrimaryKeySelective(Notice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_notice
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int updateByPrimaryKey(Notice record);

	//	æŸ¥è¯¢æ‰?œ‰è®°å½•
	List<Notice> selectAllList();

}