package cn.ticket.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import cn.ticket.entity.Orders;

@Repository
public interface OrdersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_orders
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int deleteByPrimaryKey(Long orderNum);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_orders
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int insert(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_orders
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int insertSelective(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_orders
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	Orders selectByPrimaryKey(Long orderNum);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_orders
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int updateByPrimaryKeySelective(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_orders
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int updateByPrimaryKey(Orders record);

	//	根据帐户 初始记录索引 查询list
	List<Orders> selectByNeed(String account,Long start);
	
//	根据日期 初始索引�?查询list
	List<Orders> selectOrderList(String date,Long start);
	
//	根据日期 获取记录总数
	Long getOrderNum(String date);
	
//	根据帐号获取记录总数
	Long selectByNeedCount(String account);
	
//	根据帐号 订单状�?获取记录总数
	Long selectByStatusCount(String account,Integer status);
	
//	根据帐号 初始记录�?�� 订单状�?获取 list
	List<Orders> selectOrderListByStatus(String account,Long statrt,Integer status);

}