package cn.ticket.dao;

import org.springframework.stereotype.Repository;

import cn.ticket.entity.PassagerInfo;

@Repository
public interface PassagerInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_passager_info
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_passager_info
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int insert(PassagerInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_passager_info
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int insertSelective(PassagerInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_passager_info
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	PassagerInfo selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_passager_info
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int updateByPrimaryKeySelective(PassagerInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_passager_info
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int updateByPrimaryKey(PassagerInfo record);
}