package cn.ticket.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import cn.ticket.entity.Tickets;

@Repository
public interface TicketsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_ticket
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int deleteByPrimaryKey(Long Id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_ticket
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int insert(Tickets record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_ticket
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int insertSelective(Tickets record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_ticket
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	Tickets selectByPrimaryKey(Long Id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_ticket
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int updateByPrimaryKeySelective(Tickets record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_ticket
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int updateByPrimaryKey(Tickets record);

	//	根据出发�?目的�?日期 获取 list
	List<Tickets> selectByNeed(String departPlace, String destination,
			String date);

//	根据 出发�?日期获取list
	List<Tickets> selectByNeed_1(String departPlace, String date);

//	更新车次状�?
	boolean updateBusType(String trainsNum, int type);

//	根据 车次�?日期 出发时间 获取记录总数
	Long queryForId(String trainsNum, String date, String departTime);

//	根据车次号删除车次相关车�?
	int deleteByTrainsNum(String trainsNum);

//	查询常规�?
	List<Tickets> selectAllTicketsByCommon();

//	查询�?��车票
	List<Tickets> selectAllTickets();
}