package cn.ticket.dao;

import org.springframework.stereotype.Repository;

import cn.ticket.entity.Users;

@Repository
public interface UsersMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_users
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int deleteByPrimaryKey(String account);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_users
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int insert(Users record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_users
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int insertSelective(Users record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_users
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	Users selectByPrimaryKey(String account);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_users
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int updateByPrimaryKeySelective(Users record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table table_wxs_users
	 * @mbggenerated  Wed Feb 22 12:45:51 CST 2017
	 */
	int updateByPrimaryKey(Users record);
}